// import { ethers } from "ethers";
export const ProgressBarWrapper = {
  mt: "15px",

  "& > p": {
    color: "#291F14",
    fontSize: "15px",
    fontWeight: 700,
    textAlign: "center",
    // pb: "10px",
    py: "8px",
    my: "15px",
    backgroundColor: "#ffffff",
    borderRadius: "50px",
    "& .UsdtRaisedNumber": {
      color: "#26A17B",
      fontSize: "15px",
      fontWeight: 700,
    },
  },
  "& .ProgressWrapper": {
    width: { xs: "calc(100% - 8px)", sm: "100%" },
    position: "relative",
    backgroundColor: "#ffffff",
    borderRadius: "50px",
    p: "4px",
    "& .MuiLinearProgress-root": {
      height: "30px",
      backgroundColor: "transparent",
      borderRadius: "50px",
      "& .MuiLinearProgress-bar": {
        backgroundColor: "#26A17B",
        borderRadius: "50px",
      },
    },
    "& > p": {
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "0",
      right: "0",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#281606",
      fontWeight: 700,
      fontSize: "16px",
    },
  },
};
export const divider = {
  "& p": {
    position: "relative",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#291F14",
    fontSize: "15px",
    fontWeight: 700,
    paddingTop: "15px",
    paddingBottom: "15px",
    "&:after": {
      content: "''",
      position: "absolute",
      width: "calc(50% - 90px)",
      height: "1px",
      backgroundColor: "#291F14",
      left: "0",
      // top: "50%",
    },
    "&:before": {
      content: "''",
      position: "absolute",
      width: "calc(50% - 90px)",
      height: "1px",
      backgroundColor: "#291F14",
      right: "0",
      // top: "50%",
    },
  },
};
export const PaymentBtnWrapper = {
  display: "flex",
  alignItems: "stretch",
  flexWrap: "wrap",
  justifyContent: "center",
  alignContent: "center",

  "& button": {
    backgroundColor: "#ffffffa6",
    borderRadius: "50px",
    marginRight: "5px",
    marginLeft: "5px",
    padding: "7px 26px 7px",
    marginBottom: "15px",
    border: "2px solid #ffffff00",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "130px",
    height: "calc(100% - 15px)",
    "& img": { mr: "7px" },
    "&.Selected": { border: "2px solid #F39F19" },
    "& .Title": {
      color: "#281606",
      fontSize: "18px",
      fontWeight: 700,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      lineHeight: 1,
      "& .SubTitle": {
        color: "#281606",
        fontSize: "10px",
        fontWeight: 700,
        lineHeight: 1,
      },
    },
  },
  "& .BtnWrapper": {
    "&:nth-of-type(3),:nth-of-type(6)": {
      "& button": { "& img": { mr: "0" } },
    },
  },
};
export const InputWrapper = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexDirection: { xs: "column", sm: "row" },
  gap: "10px",
  mt: "10px",
  "& .InputInnerWrapper": {
    "& label": {
      // color: "#B76229",
      color: "#000",

      fontSize: "12px",
      fontWeight: 600,
      textAlign: "center",
      marginBottom: "6px",
      "& span": { fontWeight: 800 },
    },
    "& input": {
      backgroundColor: "#ffffffcc",
      borderRadius: "50px",
      padding: "14px 60px 14px 19px",
      color: "#A67D52",
      fontWeight: 700,
    },
    "& fieldset": { display: "none" },
    "& input::-webkit-outer-spin-button, input::-webkit-inner-spin-button": {
      WebkitAppearance: "none",
      margin: "0",
    },
  },
};
export const BuyWrapper = {
  textAlign: "center",
  marginTop: "15px",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  mt: "15px",
  "& p": {
    // color: "#B76229",
    color: "#000",

    fontSize: "12px",
    fontWeight: 600,
    textAlign: "center",
    marginBottom: "6px",
    lineHeight: 1,
  },
  "& .errorstate": {
    color: "#ff0000",
    fontWeight: "bold",
  },
  "& h5": {
    color: "#281606",
    fontSize: "15px",
    fontWeight: 700,
    textAlign: "center",
    marginBottom: "6px",
  },
  "& button": {
    background:
      "linear-gradient(180deg, #89CFF0 -52.31%, #85CDEE -12.72%, #7AC6E8 21.75%, #69BCDE 54.22%, #50AED0 85.41%, #309BBE 115.5%, #1F92B5 129%)",
    borderRadius: "50px",
    color: "#ffffff",
    fontSize: "20px",
    fontWeight: 700,
    padding: { xs: "9px 55px 7px", sm: "9px 90px 7px" },
    // marginTop: "15px",
    minWidth: "230px",
  },
};

export const TimerWrapper = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  "& p": {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderLeft: "1px solid #291F14",
    paddingLeft: { xs: "10px", sm: "20px" },
    paddingRight: { xs: "10px", sm: "20px" },
    color: "#B76229",
    fontSize: "14px",
    fontWeight: 400,
    paddingTop: "3px",
    paddingBottom: "1px",
    "&:last-child": { borderRight: "1px solid #291F14" },
    "& span": {
      color: "#291F14",
      fontWeight: 700,
      fontSize: "38px",
      lineHeight: 1,
    },
  },
};
